# Copyright 2019 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

################################################################################
##                               BUILD ARGS                                   ##
################################################################################
# This build arg allows the specification of a custom Golang image.
ARG GOLANG_IMAGE=golang:1.24.2

# This build arg allows the specification of a custom base image.
ARG BASE_IMAGE=photon:5.0

################################################################################
##                              BUILD STAGE                                   ##
################################################################################
# Build the CSI driver with VDDK support (requires CGO)
FROM ${GOLANG_IMAGE} as builder

# This build arg is the version to embed in the CSI binary
ARG VERSION=unknown

# This build arg controls the GOPROXY setting
ARG GOPROXY

# Copy VDDK libraries into the build stage
# Build context is set to the parent directory (github.com/)
COPY kubernetes-sigs/vsphere-csi-driver/.libs/vmware-vix-disklib-distrib /usr/local/vmware-vix-disklib-distrib

# Set up Go workspace to match the expected module path structure
WORKDIR /go/src/github.com/kubernetes-sigs/vsphere-csi-driver

# Copy virtual-disks dependency (maintains go.mod replace directive)
COPY vmware/virtual-disks /go/src/github.com/vmware/virtual-disks

# Copy go.mod and go.sum first for better layer caching
COPY kubernetes-sigs/vsphere-csi-driver/go.mod kubernetes-sigs/vsphere-csi-driver/go.sum ./
RUN go mod download

# Copy source code
COPY kubernetes-sigs/vsphere-csi-driver/pkg/    pkg/
COPY kubernetes-sigs/vsphere-csi-driver/cmd/    cmd/

# Build with CGO enabled for VDDK support
ENV CGO_ENABLED=1
ENV GOFIPS=1
ENV GOEXPERIMENT="boringcrypto"
ENV GOPROXY=${GOPROXY:-https://proxy.golang.org}
ENV CGO_CFLAGS="-I/usr/local/vmware-vix-disklib-distrib/include"
ENV CGO_LDFLAGS="-L/usr/local/vmware-vix-disklib-distrib/lib64 -lvixDiskLib -ldl -Wl,-rpath,/usr/local/vmware-vix-disklib-distrib/lib64"

RUN go build -ldflags="-w -s -X sigs.k8s.io/vsphere-csi-driver/v3/pkg/csi/service.Version=${VERSION}" \
    -o vsphere-csi ./cmd/vsphere-csi

################################################################################
##                               MAIN STAGE                                   ##
################################################################################
FROM ${BASE_IMAGE}

# This build arg is the git commit to embed in the CSI binary
ARG GIT_COMMIT

LABEL git_commit=$GIT_COMMIT
LABEL "maintainers"="Divyen Patel <divyenp@vmware.com>, Sandeep Pissay Srinivasa Rao <ssrinivas@vmware.com>, Xing Yang <yangxi@vmware.com>"

RUN tdnf -y upgrade

# Install required packages for CSI driver functionality
RUN tdnf -y install \
  nfs-utils \
  util-linux \
  e2fsprogs \
  xfsprogs

# Copy VDDK libraries to the runtime image
COPY --from=builder /usr/local/vmware-vix-disklib-distrib/lib64 /usr/local/vmware-vix-disklib-distrib/lib64

# Set library path for VDDK
ENV LD_LIBRARY_PATH=/usr/local/vmware-vix-disklib-distrib/lib64:${LD_LIBRARY_PATH}

# Copy the binary
COPY --from=builder /go/src/github.com/kubernetes-sigs/vsphere-csi-driver/vsphere-csi /bin/vsphere-csi

# Remove cached data
RUN tdnf clean all

ENTRYPOINT ["/bin/vsphere-csi"]

