//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionInfo) DeepCopyInto(out *EncryptionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionInfo.
func (in *EncryptionInfo) DeepCopy() *EncryptionInfo {
	if in == nil {
		return nil
	}
	out := new(EncryptionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceInfo) DeepCopyInto(out *PerformanceInfo) {
	*out = *in
	if in.IopsLimit != nil {
		in, out := &in.IopsLimit, &out.IopsLimit
		*out = new(int64)
		**out = **in
	}
	if in.DiskStripes != nil {
		in, out := &in.DiskStripes, &out.DiskStripes
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceInfo.
func (in *PerformanceInfo) DeepCopy() *PerformanceInfo {
	if in == nil {
		return nil
	}
	out := new(PerformanceInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassProperties) DeepCopyInto(out *StorageClassProperties) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassProperties.
func (in *StorageClassProperties) DeepCopy() *StorageClassProperties {
	if in == nil {
		return nil
	}
	out := new(StorageClassProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageClassProperties) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassPropertiesList) DeepCopyInto(out *StorageClassPropertiesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StorageClassProperties, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassPropertiesList.
func (in *StorageClassPropertiesList) DeepCopy() *StorageClassPropertiesList {
	if in == nil {
		return nil
	}
	out := new(StorageClassPropertiesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StorageClassPropertiesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassPropertiesSpec) DeepCopyInto(out *StorageClassPropertiesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassPropertiesSpec.
func (in *StorageClassPropertiesSpec) DeepCopy() *StorageClassPropertiesSpec {
	if in == nil {
		return nil
	}
	out := new(StorageClassPropertiesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassPropertiesStatus) DeepCopyInto(out *StorageClassPropertiesStatus) {
	*out = *in
	if in.StorageTypeInfo != nil {
		in, out := &in.StorageTypeInfo, &out.StorageTypeInfo
		*out = new(StorageTypeInfo)
		**out = **in
	}
	if in.VolumeTypeInfo != nil {
		in, out := &in.VolumeTypeInfo, &out.VolumeTypeInfo
		*out = new(VolumeTypeInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologyInfo != nil {
		in, out := &in.TopologyInfo, &out.TopologyInfo
		*out = new(TopologyInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.EncryptionInfo != nil {
		in, out := &in.EncryptionInfo, &out.EncryptionInfo
		*out = new(EncryptionInfo)
		**out = **in
	}
	if in.PerformanceInfo != nil {
		in, out := &in.PerformanceInfo, &out.PerformanceInfo
		*out = new(PerformanceInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassPropertiesStatus.
func (in *StorageClassPropertiesStatus) DeepCopy() *StorageClassPropertiesStatus {
	if in == nil {
		return nil
	}
	out := new(StorageClassPropertiesStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageTypeInfo) DeepCopyInto(out *StorageTypeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageTypeInfo.
func (in *StorageTypeInfo) DeepCopy() *StorageTypeInfo {
	if in == nil {
		return nil
	}
	out := new(StorageTypeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyInfo) DeepCopyInto(out *TopologyInfo) {
	*out = *in
	if in.AccessibleZones != nil {
		in, out := &in.AccessibleZones, &out.AccessibleZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BackingZones != nil {
		in, out := &in.BackingZones, &out.BackingZones
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyInfo.
func (in *TopologyInfo) DeepCopy() *TopologyInfo {
	if in == nil {
		return nil
	}
	out := new(TopologyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeTypeInfo) DeepCopyInto(out *VolumeTypeInfo) {
	*out = *in
	if in.SupportedAccessModes != nil {
		in, out := &in.SupportedAccessModes, &out.SupportedAccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SupportedVolumeModes != nil {
		in, out := &in.SupportedVolumeModes, &out.SupportedVolumeModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.FileSystemTypes != nil {
		in, out := &in.FileSystemTypes, &out.FileSystemTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeTypeInfo.
func (in *VolumeTypeInfo) DeepCopy() *VolumeTypeInfo {
	if in == nil {
		return nil
	}
	out := new(VolumeTypeInfo)
	in.DeepCopyInto(out)
	return out
}
